### PR TITLE
purescript-mode stocktaking

### PR DESCRIPTION
**Pull request by kritzcreek**
# Taking Stock. Where are we at?

Until GitHub "unforks" this repository we'll have to move discussions into PR's
because forks fon't have "Issues".

I'd like to pick up development on `purescript-mode`. In it's current state it's
basically a big rename of the haskell-mode codebase from May 2014. It's actually
_ridiculous_ how well that's been working for so long, but I'd like to pick
development back up and see if we can't do better.

I'm a fairly unexperienced elisp hacker so expect mistakes to be made, and
lessons to be learned, but I'm confident that we'll have a lot of fun while
doing so!

To pick purescript-mode back up I devised the following plan:
1. Take Stock
   
   Collect the features people are actually using and radically prune
   everything we don't need right now.
2. Clean up the codebase
   
   I think it's fair to assume a minimum of Emacs 24 or greater
   
   We also want to remove everything that is GHC/Haskell specific and doesn't
   apply to PureScript
3. Move psc-ide-mode into purescript-mode
   
   psc-ide is distributed with the compiler and so I think it's fine to treat
   is as the _blessed_ tool and integrate support right inside purescript-mode
4. Maintenance/New Features

For this PR I'd like to start with point 1. Comment on this PR with the
functionality you are using, share the link so that we hopefully reach most/all
the purescript-mode users and collect the features they are actively using.

I've checked the features I'm already using and will check whatever features you
are using right now.
## What functionality is actually being used?
- [X] Syntax Highlighting
- [X] Indentation
  
  I think we should decide on having one indentation mode and having it
  activated by default.
  - purescript-indentation
  - purescript-indent
  - purescript-simple-indent
- [ ] Import handling
  - Align imports (formatting)
  - Navigate imports
- [ ] Move nested
- [ ] Package (currently cabal support)
  
  I could imagine us integrating with pulp and maybe psc-package here, but the
  existing code will need to be removed
- [ ] Declaration Scanning
  
  I think this is superseeded by psc-ide go-to definition, but I'm happy to be
  proven wrong.
- [ ] Presentation mode
  
  Not sure what this really does, but I haven't ever used it
- [ ] purescript-show.el
  No idea what this is supposed to be
- [X] Unicode input method
  
  I've been using this before, but I replaced it with a custom
  search-and-replace query since it stopped company from working. I think it
  would be cool to make this work properly.
- [ ] Snippets
  
  The snippets inside `purescript-yas.el` are very GHC specific and should be
  removed. We should be able to salvage the snippets under
  snippets/haskell-mode though, and there seem to be a few nice ones there.

This won't work without your help, but I'm confident that we can do it,
especially after all the help and kindness I've experienced working on
psc-ide-mode.

If you have questions/suggestions or if I've forgotten to mention any important
functionality let me know aswell!

### CODE REVIEW

**Comment by FrigoEU** [comment]
I recently switched to Emacs (spacemacs) and am using only syntax highlighting and indentation. The indentation doesn't work particularly well for me though, so I do a lot of it by hand. I also use only the psc-ide goto. Don't use unicode stuff myself.

**Comment by bodil** [comment]
I only use indentation and highlighting, I depend on psc-ide for just about everything else.

What do you think about https://github.com/emacs-pe/purescript-mode ? Not sure which alternative is preferable as a starting point. I've mostly just used purescript-mode since the start and not thought much about it.

**Comment by ElvishJerricco** [comment]
Yea I've been using https://github.com/emacs-pe/purescript-mode. It's been good so far.

**Comment by kRITZCREEK** [comment]
After looking through https://github.com/emacs-pe/purescript-mode I think it's pretty much just `purescript-font-lock.el` and `purescript-mode.el` copied across so it doesn't really matter where we start.

**Comment by epost** [comment]
I talked to one of the maintainers of haskell-mode last year and he advised against building on it, saying instead that idris-mode was much better. I can't remember the specifics off the top of my head -- probably something to do with the protocol -- but it may be advice worth heeding. I've been using the emacs-pe version myself for a few months now btw, and it seems to be more stable.

**Comment by bodil** [comment]
I can certainly vouch for the quality of idris-mode.

**Comment by kRITZCREEK** [comment]
@epost If the `idris-mode` advice is about the protocol it won't matter for us here, since comunication with `psc-ide` works fine with `psc-ide-emacs`. I'll take a look at idris-mode however but I'm not sure how well this aligns with PureScript since `idris-mode` relies heavily on compiler interaction for most of its features (even syntax highlighting).

> I've been using the emacs-pe version myself for a few months now btw, and it seems to be more stable.

Would you expand on that? The code in `dysinger/purescript-mode` hasn't really changed for the last 2 years. Does it get more sta(b)le?

**Comment by naehrstoff** [comment]
As someone relatively new to Purescript, it took me a while to find a setup that worked well for me. For Haskell I have a four-line `use-package` declaration that sets up everything using `intero` and it just works. For Purescript, I have `purescript-mode`, `flycheck-purescript`, and `psc-ide`, as well as a bit of guilt for not having setup `pscid` yet because it would probably be useful. To figure out how this all fits together took me a while and I would greatly appreciate a simpler setup.

For the indentation, I'm using `haskell-indentation-mode` because that's what ended up working. I don't know what I'm missing out on by not using a more specific mode.

One specialty in my setup is that I'm providing `psc-ide` from `node_modules`. This is important to me as we build many projects a year (mostly JS currently, though) and by the time I get back to one it should just work with the bundled and possibly out-of-date binaries and not rely on a global one.

I'm attaching a copy of my Purescript setup to provide a glance at what I ended up with (I just set this up last week). This might give you pointers on things I'm doing wrong that could influence the design and documentation of `purescript-mode` 😊 In general, I'm very much for a mode that uses sensible defaults.

```
(use-package purescript-mode
  :ensure t
  :commands purescript-mode
  :mode (("\\.purs$" . purescript-mode)))

(use-package flycheck-purescript
  :ensure t
  :after purescript-mode
  :init
  (eval-after-load 'flycheck
    '(add-hook 'flycheck-mode-hook #'flycheck-purescript-setup))
  :config
  (add-hook 'purescript-mode-hook
            (lambda ()
              (setq default-directory
                    (locate-dominating-file default-directory "node_modules")))))

(use-package psc-ide
  :ensure t
  :after purescript-mode
  :config
  (add-hook 'purescript-mode-hook
            (lambda ()
              (my/use-psc-ide-from-node-modules)
              (psc-ide-mode t)
              (company-mode t)
              (flycheck-mode t)
              (haskell-indentation-mode t))))

(defun my/use-psc-ide-from-node-modules ()
  "Find psc-ide binaries of current project by searching for node_modules."
  (let* ((root (locate-dominating-file
                (or (buffer-file-name) default-directory)
                "node_modules"))
         (client (and root
                      (expand-file-name "node_modules/purescript/bin/psc-ide-client.js"
                                        root)))
         (server (and root
                      (expand-file-name "node_modules/purescript/bin/psc-ide-server.js"
                                        root))))
    (when (and client (file-executable-p client) server (file-executable-p server))
      (setq-local psc-ide-client client)
      (setq-local psc-ide-server server))))

(provide 'lang-purescript)
```

**Comment by epost** [comment]
@kRITZCREEK I used to have weird issues with purescript-mode, probably as I upgraded packages or emacs itself, to the extent that it would often become unusable. I can't remember the specifics I'm afraid, although I figured that since purescript-mode was basically haskell-mode after a search and replace, it's hardly surprising that stuff should go awry at some point. It's a pretty complicated codebase, after all.

**Comment by kRITZCREEK** [comment]
@naehrstoff Thanks so much for sharing this, uncovers the spots where I need to document properly :)

`flycheck-purescript` should be superseeded by `psc-ide-mode`'s flycheck integration.

`psc-ide-client` is no longer used and can be safely removed, I'll remove it from `psc-ide-emacs` aswell.

Your grabbbing the binaries from `node_modules` code is awesome :) Is it fine if I feel inspired by it and add it to `psc-ide-mode` for now? ;)

I'll take a look at `haskell-indentation-mode` and how it has changed from `purescript-indentation-mode`.

If you need help with `pscid` let me know, but you probably don't really need `pscid` with all the setup in your editor, it's meant for a more terminal focused workflow.

@epost Oh so there might be conflicts with other packages then? This situation might improve once we get rid of the cruft ;)

**Comment by naehrstoff** [comment]
@kRITZCREEK Glad that this helps 😄 The grabbing binaries is something I first saw in @bodil's [ohai-emacs](https://github.com/bodil/ohai-emacs/blob/master/modules/ohai-purescript.el) and then gradually put together from other people's `.emacs` files. This can certainly be better abstracted as Bodil shows, but I wanted to understand it first.

Thanks for working on this mode, I'm looking forward to the results!

**Comment by mjhoy** [comment]
As a new user, I find the import handling super useful (adding imports based on company completion). Also the weird and magical `C-c M-s`, psc-ide-flycheck-insert-suggestion, mostly for cleaning up unused import warnings.

**Comment by naehrstoff** [comment]
I just discovered today that this mode has a function `purescript-sort-imports` that sorts differently (purely alphabetical) than `psc-ide-mode` (sorted by unqualified -> qualified -> explicit import list).

I mostly use `psc-ide-mode` to handle my imports, but from time to time when I wanted to clean it up, I used `purescript-sort-imports`, not understanding at first that the two work against each other.

I think `purescript-sort-imports` should either be removed (Emacs has other facilities to sort a region, after all) or aligned with `psc-ide-mode` (which I guess just uses what `pscid` provides it with?).

**Comment by vyorkin** [comment]
I understand that this might not be the right place to report issues, but I observe a very strange behavior of `Purescript-Indentation`. I'm relatively new to emacs, elisp and purescript, so idk if I can't provide more info except the gif + [link to my dotfiles](https://github.com/vyorkin-personal/d/blob/master/tag-emacs/emacs.d/init.el#L1319).

purs-indent
 
my psc-ide-mode config:

```
(use-package psc-ide
  :preface
  (defun rc/psc-ide/setup ()
    (psc-ide-mode)
    (turn-on-purescript-indentation)) ;; <<<
  :after purescript-mode
  :init
  (setq psc-ide-use-npm-bin t)
  :config
  (add-hook 'purescript-mode-hook 'rc/psc-ide/setup))
```

**Comment by mjhoy** [comment]
@vyorkin hmm, i don't see that behavior, and i think i have a similar config:

https://github.com/mjhoy/dotfiles/blob/master/emacs.d/lisp/init-purescript.el

**Comment by tungd** [comment]
@vyorkin that is caused by Evil actually. The feature is `evil-auto-indent` however it doesn't work well for PureScript mode (and even Haskell mode). You can turn it off for PS and Haskell with the following snippet:

```
(defun turn-off-evil-auto-indent ()
  (setq-local evil-auto-indent nil))

(add-hook 'haskell-mode-hook #'turn-off-evil-auto-indent)
(add-hook 'purescript-mode-hook #'turn-off-evil-auto-indent)
```

**Comment by vyorkin** [comment]
yeah, it works perfectly without `evil-auto-indent`, thanks @tungd !

**Comment by vyorkin** [comment]
today I've tried `turn-on-purescript-unicode-input-method` and noticed the it doesn't seem to work correctly when using superclasses, e.g.:
```
class Eq a ≤ Hashable a where
```
the arrow was substituted for `≤` which I guess is incorrect:
```
  13  class Eq a ≤ Hashable a where

  Unable to parse module:
  unexpected ≤
  expecting indentation at column 1 or end of input
```
btw, it is ok to report issues here?

**Comment by karljs** [comment]
I hope it's okay to report another issue here.

When I rewrap comments using `fill-paragraph` (`M-q`) it doesn't respect the Pursuit syntax (`-- |`) with the pipe character.

```
-- | Long comment split
-- | across lines.
```

becomes something like

```
-- | Long comment split | across
-- lines
```

rather than the preferred

```
-- | Long comment split across
-- | lines
```

**Comment by kRITZCREEK** [comment]
@karljs Yeah, that one annoys me as well, do you have any idea how to fix it? I don't really know how to do emacs's syntax table thing...

**Comment by karljs** [comment]
@kRITZCREEK I'm not sure we even need to mess with the syntax table to fix this.  I think it's enough to change the regexp set in the variable `comment-start-skip` to allow a pipe character.  I've never actually written a major mode so I could be totally wrong.

Maybe we could set it to something like `"[-{]-[\s-]*|?[\s-]*"`

Which would say essentially:
Either `-` or `{`, followed by a `-`, followed by arbitrary whitespace, followed by zero or one pipe character, followed by arbitrary whitespace.  Some very quick and informal testing on my end suggests this works.

The relevant place to make the change (I think) is:
https://github.com/dysinger/purescript-mode/blob/2d1fa590a6de875ea4bd964349df0ba5e24fb1f3/purescript-mode.el#L321

**Comment by kritzcreek** [comment]
@karljs Thank you very much! I think I've found a simpler regex in b76c7f3 (it never worked for multiline comments in the first place)

Please let me know if you run into any more problems :)

**Pull request closed without merging**
