### PR TITLE
Disable quail rule for <= char sequence

### PR DESCRIPTION
**Pull request by vyorkin**
stupid PR but it fixes `purescript-unicode-input-method` :)

I "kinda reported" this issue [here](https://github.com/dysinger/purescript-mode/pull/8#issuecomment-353009732) a couple of days ago

I disabled [the relevant quail's rule](https://github.com/dysinger/purescript-mode/blob/master/purescript-unicode-input-method.el#L228), but maybe it could be disabled only for this particular case (when using superclasses), can't say for sure because I'm not familiar with quail

### CODE REVIEW

**Comment by vyorkin** [comment]
I'm also not sure about other Unicode operators, e.g.:
```
 ("~>"               ["⇝"])
 ("<~"               ["⇜"])
```
they don't seem to be supported either, is there a place where I can find all of them?

**Comment by vyorkin** [comment]
hm, [relational operators](https://github.com/dysinger/purescript-mode/blob/master/purescript-unicode-input-method.el#L225-L231) aren't recognized too. ok please don't merge, seems that I need some guidance here

**Comment by kRITZCREEK** [comment]
Yeah, those are the unicode symbols built into the language. I don't really know how this `quail` business works, but I've trimmed it down for my own usage like so:

https://github.com/kRITZCREEK/spacemacs-conf/blob/8e5cda8a3377eeea45cd539ef8232221a442f9f2/ps-unicode-input.el

The dot symbol in there shouldn't go into this mode, since it's from our Prelude at work. There are problems with quail though, for example it keeps changing `for` into `fro` which is super annoying, but I don't know how to get rid of that behaviour.

**Comment by vyorkin** [comment]
thanks, so I think it makes sense to keep the greek, double-stuck, numeric sub/super script mappings and remove everything else that isn't supported

**Pull request closed without merging**
